### ISSUE TITLE
throwIfFalsy should treat false and 0 as falsy

### ISSUE THREAD

**Issue by DetachHead** [jindra12/throw-expression#1]
in javascript, `0` and `false` are `falsy`, so `throwIfFalsy` should behave the same way: https://developer.mozilla.org/en-US/docs/Glossary/Falsy

though i understand the need for a function that behaves the way it currently does. perhaps a `throwIfNullOrUndefined`?

**Comment by brainthinks** [comment]
Noticed this as well - how about a `throwIfNullish` to use the same "nullish" from nullish coalescing?

**Comment by jindra12** [comment]
Done!
